version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: gulp
    versions:
    - 4.0.2
  - dependency-name: fitvids
    versions:
    - 2.1.1
  - dependency-name: natives
    versions:
    - 1.1.6
  - dependency-name: gulp-postcss
    versions:
    - 8.0.0
