const categories = [
  {
    title: 'Design',
    slug: '/category/design',
    slugAsParams: 'design',
    description:
      'From design system process to speedy quick tips. Explore craft with colour, typography and visual design.',
    parent: false,
    theme: 'rio',
    icon: 'pen',
    exclude: false,
  },
  {
    title: 'Quick tip',
    slug: '/category/quick-tip',
    slugAsParams: 'quick-tip',
    description:
      'Short posts covering a specific technique or feature to help you figure something out and get back to what you’re doing.',
    parent: 'design',
    theme: 'dandelion',
    icon: 'bolt',
    exclude: false,
  },
  {
    title: 'Colour',
    slug: '/category/colour',
    slugAsParams: 'colour',
    description:
      'Colour is a fundamental skill within interface design, it’s a balance through brand, emotion, accessibility and usabilility.',
    parent: 'design',
    theme: 'magenta',
    icon: 'palette',
    exclude: false,
  },
  {
    title: 'Process',
    slug: '/category/process',
    slugAsParams: 'process',
    description:
      'The broader topic of design process, from component composition to design and code handover.',
    parent: 'design',
    theme: 'grass',
    icon: 'component',
    exclude: false,
  },
  {
    title: 'Prototyping',
    slug: '/category/prototyping',
    slugAsParams: 'prototyping',
    description: 'Prototyping posts',
    parent: 'fern',
    theme: 'neutral-02',
    icon: 'play',
    exclude: false,
  },
  {
    title: 'Visual design',
    slug: '/category/visual-design',
    slugAsParams: 'visual-design',
    description:
      'Looking at how we design the interfaces we use and a look at the how and why behind visual techniques.',
    parent: 'design',
    theme: 'lavender',
    icon: 'vector-square',
    exclude: false,
  },
  {
    title: 'Typography',
    slug: '/category/typography',
    slugAsParams: 'typography',
    description:
      'The latest type trends, alternatives to popular typefaces and typography techniques.',
    parent: 'design',
    theme: 'neutral-02',
    icon: 'type',
    exclude: false,
  },
  {
    title: 'Code',
    slug: '/category/code',
    slugAsParams: 'code',
    description: 'Code posts',
    parent: false,
    theme: 'dandelion',
    icon: 'code',
    exclude: false,
  },
  {
    title: 'Animation',
    slug: '/category/animation',
    slugAsParams: 'animation',
    description: 'Animation posts',
    parent: 'code',
    theme: 'magenta',
    icon: 'play',
    exclude: false,
  },
  {
    title: 'CSS',
    slug: '/category/css',
    slugAsParams: 'css',
    description: 'CSS posts',
    parent: 'code',
    theme: 'grass',
    icon: 'css',
    exclude: false,
  },
  {
    title: 'Patterns',
    slug: '/category/patterns',
    slugAsParams: 'patterns',
    description: 'Patterns posts',
    parent: 'code',
    theme: 'fern',
    icon: 'puzzle',
    exclude: false,
  },
  {
    title: 'Resources',
    slug: '/category/resources',
    slugAsParams: 'resources',
    description: 'Resources posts',
    parent: 'design',
    theme: 'fern',
    icon: 'puzzle',
    exclude: false,
  },
  {
    title: 'Website',
    slug: '/category/website',
    slugAsParams: 'website',
    description: 'Website posts',
    parent: false,
    theme: 'cornflour',
    icon: 'folder',
    exclude: true,
  },
  {
    title: 'Terminal',
    slug: '/category/terminal',
    slugAsParams: 'terminal',
    description: 'Terminal posts',
    parent: false,
    theme: 'cornflour',
    icon: 'code',
    exclude: true,
  },
  {
    title: 'Everything',
    slug: '/blog',
    slugAsParams: 'blog',
    description: 'All posts',
    parent: false,
    theme: 'cornflour',
    icon: 'folder',
    exclude: false,
  },
]

export default categories
