/**
 * standard.site (AT Protocol) record lookups.
 *
 * The slug → AT-URI map in content/standard-site.json is generated by
 * scripts/sync-standard-site.js. Records are keyed by server-assigned rkeys,
 * so the map is the source of truth for verification links.
 */

import map from '@/content/standard-site.json'

export function getPublicationUri() {
  return map.publication || null
}

export function getDocumentUri(slug) {
  return map.documents?.[slug] || null
}
