import { lazy } from 'react'

export const sections = [
  {
    title: 'Foundations',
    items: [
      { id: 'colours', label: 'Colours' },
      { id: 'typography', label: 'Typography' },
      { id: 'spacing', label: 'Spacing & radius' },
      { id: 'shadows', label: 'Shadows' },
      { id: 'icons', label: 'Icons' },
      { id: 'grid', label: 'Grid & layout' },
      { id: 'dark-mode', label: 'Dark mode' },
      { id: 'utilities', label: 'Custom utilities' },
    ],
  },
  {
    title: 'Components',
    items: [
      { id: 'badge', label: 'Badge' },
      { id: 'button', label: 'Button' },
      { id: 'card', label: 'Card' },
      { id: 'category', label: 'Category' },
      { id: 'chat', label: 'Chat' },
      { id: 'chip', label: 'Chip' },
      { id: 'codepen', label: 'CodePen' },
      { id: 'contact-form', label: 'ContactForm' },
      { id: 'date', label: 'Date' },
      { id: 'figure', label: 'Figure' },
      { id: 'icon-component', label: 'Icon' },
      { id: 'link', label: 'Link' },
      { id: 'modal', label: 'Modal' },
      { id: 'newsletter-form', label: 'NewsletterForm' },
      { id: 'notepad', label: 'Notepad' },
      { id: 'pagination', label: 'Pagination' },
      { id: 'placeholder', label: 'Placeholder' },
      { id: 'social', label: 'Social' },
      { id: 'table-of-contents', label: 'Table of contents' },
    ],
  },
  {
    title: 'MDX authoring',
    items: [{ id: 'mdx-authoring', label: 'MDX authoring' }],
  },
  {
    title: 'Patterns',
    items: [{ id: 'illustration', label: 'Illustrations' }],
  },
]

export const sectionComponents = {
  colours: lazy(() => import('./colour-palette')),
  typography: lazy(() => import('./typography-section')),
  spacing: lazy(() => import('./spacing-section')),
  shadows: lazy(() => import('./shadows-section')),
  icons: lazy(() => import('./icons-section')),
  grid: lazy(() => import('./grid-section')),
  'dark-mode': lazy(() => import('./dark-mode-section')),
  utilities: lazy(() => import('./utilities-section')),
  badge: lazy(() => import('./badge-section')),
  button: lazy(() => import('./button-section')),
  card: lazy(() => import('./card-section')),
  category: lazy(() => import('./category-section')),
  chat: lazy(() => import('./chat-section')),
  chip: lazy(() => import('./chip-section')),
  codepen: lazy(() => import('./codepen-section')),
  'contact-form': lazy(() => import('./contact-form-section')),
  date: lazy(() => import('./date-section')),
  figure: lazy(() => import('./figure-section')),
  'icon-component': lazy(() => import('./icon-component-section')),
  link: lazy(() => import('./link-section')),
  modal: lazy(() => import('./modal-section')),
  'newsletter-form': lazy(() => import('./newsletter-form-section')),
  notepad: lazy(() => import('./notepad-section')),
  pagination: lazy(() => import('./pagination-section')),
  placeholder: lazy(() => import('./placeholder-section')),
  social: lazy(() => import('./social-section')),
  'table-of-contents': lazy(() => import('./table-of-contents-section')),
  'mdx-authoring': lazy(() => import('./mdx-section')),
  illustration: lazy(() => import('./illustration-section')),
}
