/**
 * Sprite16
 * Auto-generated by generate-icon-sprite.js — do not edit manually
 */
const Sprite16 = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
    style={{
      position: 'absolute',
      width: 0,
      height: 0,
      overflow: 'hidden',
      display: 'none',
    }}
    {...props}
  >
    <defs>
      <symbol id=" checkmark-16" viewBox="0 0 16 16">
        <g className="checkmark / checkmark">
          <path
            d="m3 8 3 3 7-7"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id=" checkmark-underline-16" viewBox="0 0 16 16">
        <g className="checkmark / underline">
          <path
            d="M2 15h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m3 8 3 3 7-7"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="about-16" viewBox="0 0 16 16">
        <path d="M9.84335,9.69765l-.00229-.031a4.25032,4.25032,0,0,0,1.49227-3.33334v-2c0-1.20734,0-2-.66666-2.66666a2.44912,2.44912,0,0,0-2-.66667c-.60143,0-.66029.54257-1.645.64876a2.72461,2.72461,0,0,0-2.355,2.74544V6.33333A4.25032,4.25032,0,0,0,6.15894,9.66667l-.0023.03113C6.06721,10.90871,5.223,10.908,4.063,11.26685a12.9908,12.9908,0,0,0-1.56186.59426,1.99748,1.99748,0,0,0-1.16784,1.82032V14a1,1,0,0,0,1,1H13.66667a1,1,0,0,0,1-1v-.3186a1.9975,1.9975,0,0,0-1.1678-1.82031,12.99024,12.99024,0,0,0-1.56184-.59427C10.777,10.90791,9.93278,10.90862,9.84335,9.69765Z" />
      </symbol>
      <symbol id="accessibility-16" viewBox="0 0 16 16">
        <g className="accessibility">
          <path
            d="M8 4C8.552 4 9 3.552 9 3C9 2.448 8.552 2 8 2C7.448 2 7 2.448 7 3C7 3.552 7.448 4 8 4Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M12 6C12 6 9.682 7 8 7C6.318 7 4 6 4 6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M9 7H7V11H9Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M7 11L6 14"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M9 11L10 14"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="airplane-16" viewBox="0 0 16 16">
        <g className="airplane">
          <path
            d="M15 8 5 14v-4l3-2-3-2V2l10 6Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path d="M2 8H1" className="fill-none stroke-current stroke-2 sl-r" />
          <path
            d="M13 8H8"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <circle cx="2" cy="4" r="1" className="fill-current" />
          <circle cx="2" cy="12" r="1" className="fill-current" />
        </g>
      </symbol>
      <symbol id="align-centre-16" viewBox="0 0 16 16">
        <g className="align-centre">
          <path
            d="M2 2h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M2 14h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path d="M4 6h8" className="fill-none stroke-current stroke-2 sl-r" />
          <path
            d="M4 10h8"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="align-left-16" viewBox="0 0 16 16">
        <g className="align-left">
          <path
            d="M2 2h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path d="M2 6h8" className="fill-none stroke-current stroke-2 sl-r" />
          <path
            d="M2 10h6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M2 14h10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="align-right-16" viewBox="0 0 16 16">
        <g className="align-right">
          <path
            d="M2 2h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path d="M6 6h8" className="fill-none stroke-current stroke-2 sl-r" />
          <path
            d="M8 10h6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M4 14h10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="all-16" viewBox="0 0 16 16">
        <g className="all">
          <path
            d="M6 2H2v4h4V2Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 2h-4v4h4V2Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 10H2v4h4v-4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 10h-4v4h4v-4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="angle-down-16" viewBox="0 0 16 16">
        <g className="angle-down">
          <path
            d="m2 5 6 6 6-6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="angle-left-16" viewBox="0 0 16 16">
        <g className="angle-left">
          <path
            d="M10 2 4 8l6 6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="angle-right-16" viewBox="0 0 16 16">
        <g className="angle-right">
          <path
            d="m6 2 6 6-6 6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="angle-up-16" viewBox="0 0 16 16">
        <g className="angle-up">
          <path
            d="m2 11 6-6 6 6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="arrow-down-16" viewBox="0 0 16 16">
        <g className="arrow-down">
          <path
            d="M8 14V2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m4 10 4 4 4-4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="arrow-left-16" viewBox="0 0 16 16">
        <g className="arrow-left">
          <path
            d="M2 8h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 4 2 8l4 4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="arrow-right-16" viewBox="0 0 16 16">
        <g className="arrow-right">
          <path
            d="M14 8H2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m10 12 4-4-4-4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="arrow-up-16" viewBox="0 0 16 16">
        <g className="arrow-up">
          <path
            d="M8 2v12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M12 6 8 2 4 6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="autolayout-h-16" viewBox="0 0 16 16">
        <g className="autolayout / h">
          <rect
            width="4"
            height="12"
            x="2"
            y="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
          <rect
            width="4"
            height="12"
            x="10"
            y="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
        </g>
      </symbol>
      <symbol id="autolayout-v-16" viewBox="0 0 16 16">
        <g className="autolayout / v">
          <rect
            width="12"
            height="4"
            x="2"
            y="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
          <rect
            width="12"
            height="4"
            x="2"
            y="10"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
        </g>
      </symbol>
      <symbol id="blog-16" viewBox="0 0 16 16">
        <polygon
          className="fill-s1"
          points="10.667 13.333 5.333 13.333 3 7 8 1 13 7 10.667 13.333"
        />
        <rect
          x="4"
          y="13"
          width="8"
          height="2"
          transform="translate(16 28) rotate(180)"
        />
        <line x1="8" y1="1" x2="8" y2="8" />
      </symbol>
      <symbol id="bolt-16" viewBox="0 0 16 16">
        <g className="bolt">
          <path
            d="M9 6 8 1l-5 9h4l1 5 5-9H9Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="book-16" viewBox="0 0 16 16">
        <path
          stroke="color(display-p3 .0353 .1804 .1412)"
          d="M12 14V9H3v4a1 1 0 0 0 1 1h8Zm-1 0h2"
          className="slc-r sl-r stroke-2"
        />
        <path
          className="fill-(--icon-fill) stroke-2"
          stroke="color(display-p3 .0353 .1804 .1412)"
          d="M13 11V2H4a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h9Z"
        />
      </symbol>
      <symbol id="bookmark-16" viewBox="0 0 16 16">
        <g className="bookmark">
          <path
            d="M5 2H11V14L8 12L5 14Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="box-16" viewBox="0 0 16 16">
        <g className="box">
          <path
            d="M4 14a1 1 0 0 1-1-1V6h10v7a1 1 0 0 1-1 1H4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path d="M6 9h4" className="stroke-current stroke-2" />
          <path
            d="M2.5 6a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5h-11Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="bulb-16" viewBox="0 0 16 16">
        <g className="bulb">
          <path
            d="M8 1.159C6 1.159 4 2.492 4 5.159C4 7.825 6 7.825 6 10.492V12H10V10.492C10 7.825 12 7.825 12 5.159C12 2.492 10 1.159 8 1.159Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M10 13C10 14 9 15 8 15C7 15 6 14 6 13C6 12.381 6 12 6 12H10C10 12 10 12.381 10 13Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="calendar-16" viewBox="0 0 16 16">
        <g className="calendar">
          <rect
            width="12"
            height="10"
            x="2"
            y="3"
            className="fill-current stroke-current stroke-2 sl-r"
            rx="1"
          />
          <path
            d="M3 5h10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <rect
            width="10"
            height="6"
            x="3"
            y="6"
            className="fill-(--icon-fill)"
            rx=".5"
          />
        </g>
      </symbol>
      <symbol id="caret-down-16" viewBox="0 0 16 16">
        <g className="caret-down">
          <path
            d="m12 6-4 6-4-6h8Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="caret-left-16" viewBox="0 0 16 16">
        <g className="caret-left">
          <path
            d="M10 4 4 8l6 4V4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="caret-right-16" viewBox="0 0 16 16">
        <g className="caret-right">
          <path
            d="m6 4 6 4-6 4V4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="caret-up-16" viewBox="0 0 16 16">
        <g className="caret-up">
          <path
            d="M12 11 8 5l-4 6h8Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="category-16" viewBox="0 0 16 16">
        <rect className="b" x="1" y="6" width="14" height="8" />
        <polygon className="b" points="15 6 1 6 1 2 7 2 7.667 3 15 3 15 6" />
      </symbol>
      <symbol id="checkbox-16" viewBox="0 0 16 16">
        <title>checkbox</title>
        <polyline points="3 8 6 11 13 4" />
      </symbol>
      <symbol id="checkmark-16" viewBox="0 0 16 16">
        <g className="checkmark">
          <path
            d="m3 8 3 3 7-7"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="clipboard-16" viewBox="0 0 16 16">
        <g className="clipboard">
          <path
            d="M3 2h10v12H3z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M7 2h2v1H7z"
            className="fill-none stroke-current stroke-2 sl-s"
          />
        </g>
      </symbol>
      <symbol id="clipboard-success-16" viewBox="0 0 16 16">
        <g className="clipboard-success">
          <path d="M3 2h10v12H3z" className="fill-success" />
          <path
            d="M7 2h2v1H7z"
            className="fill-none stroke-current stroke-2 sl-s"
          />
          <path
            d="m6 9 1 1 3-3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="close-16" viewBox="0 0 16 16">
        <g className="close">
          <path d="M12 12 4 4" className="stroke-current stroke-2 sl-r" />
          <path d="m12 4-8 8" className="stroke-current stroke-2 sl-r" />
        </g>
      </symbol>
      <symbol id="cmd-16" viewBox="0 0 16 16">
        <g className="cmd">
          <path
            d="M4 14a2 2 0 0 0 2-2V4a2 2 0 1 0-2 2h8a2 2 0 1 0-2-2v8a2 2 0 1 0 2-2H4a2 2 0 1 0 0 4Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="code-16" viewBox="0 0 16 16">
        <g className="code">
          <rect
            width="14"
            height="12"
            x="1"
            y="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
          <path
            d="m5 6 2 2-2 2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M9 10h2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="collections-16" viewBox="0 0 16 16">
        <g className="collections">
          <path
            d="M7 3H3v11h4V3Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M10.864 3 7 4.035 9.686 14.06l3.864-1.035L10.864 3Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="comment-16" viewBox="0 0 16 16">
        <g className="comment">
          <path
            d="M11 2H5a3 3 0 0 0-3 3v8a1 1 0 0 0 1.6.8l1.333-1a4 4 0 0 1 2.4-.8H11a3 3 0 0 0 3-3V5a3 3 0 0 0-3-3Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="component-16" viewBox="0 0 16 16">
        <g className="component">
          <path
            d="m5 5 3-3 3 3-3 3z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="m2 8 3-3 3 3-3 3z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="m5 11 3-3 3 3-3 3z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="m8 8 3-3 3 3-3 3z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="component-instance-16" viewBox="0 0 16 16">
        <g className="component / instance">
          <path
            d="M7.293 1.636a1 1 0 0 1 1.414 0l5.657 5.657a1 1 0 0 1 0 1.414l-5.657 5.657a1 1 0 0 1-1.414 0L1.636 8.707a1 1 0 0 1 0-1.414l5.657-5.657Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="contact-16" viewBox="0 0 16 16">
        <polyline
          className="fill-s1 sw-2"
          points="2 5.286 1 6 1 15 15 15 15 6 13.999 5.285"
        />
        <polygon
          className="fill-(--icon-fill)"
          points="14 7 14 3 2 3 2 7 1 7 8 11 15 7 14 7"
        />
        <polyline className="sw-2" points="1 7 8 11 15 7" />
        <line className="sw-2" x1="10.79676" y1="2.99769" x2="8" y2="1" />
        <line className="sw-2" x1="8" y1="1" x2="5.20058" y2="2.99958" />
        <polyline className="sw-2" points="2 7 2 3 14 3 14 7" />
      </symbol>
      <symbol id="copy-16" viewBox="0 0 16 16">
        <g className="copy">
          <path
            d="M5 6H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <rect
            width="8"
            height="8"
            x="6"
            y="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
        </g>
      </symbol>
      <symbol id="copy-alternate-16" viewBox="0 0 16 16">
        <g className="copy-alternate">
          <path
            d="M5 6H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <rect
            width="8"
            height="8"
            x="6"
            y="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
        </g>
      </symbol>
      <symbol id="copy-success-16" viewBox="0 0 16 16">
        <g className="copy-success">
          <path d="M3 2h10v12H3z" className="fill-success" />
          <path
            d="M7 2h2v1H7z"
            className="fill-none stroke-current stroke-2 sl-s"
          />
          <path
            d="m6 9 1 1 3-3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="css-16" viewBox="0 0 16 16">
        <g className="css">
          <path
            d="M4 2h8v4l2 2-2 2v4H4v-4L2 8l2-2V2Z"
            className="fill-(--icon-fill)"
          />
          <path
            d="M6 2h-.5A1.5 1.5 0 0 0 4 3.5v2.293a.5.5 0 0 1-.146.353l-1.5 1.5a.5.5 0 0 0 0 .708l1.5 1.5a.5.5 0 0 1 .146.353V12.5A1.5 1.5 0 0 0 5.5 14H6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M10 2h.5A1.5 1.5 0 0 1 12 3.5v2.293a.5.5 0 0 0 .146.353l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 0-.146.353V12.5a1.5 1.5 0 0 1-1.5 1.5H10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="cursor-16" viewBox="0 0 16 16">
        <g className="cursor">
          <path
            d="m3.606 1.988 10.404 6.07-6.069.866-3.468 5.202-.867-12.138Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="date-16" viewBox="0 0 16 16">
        <path
          className="stroke-currentcolor fill-s1"
          d="M14,15H2a1,1,0,0,1-1-1V3H15V14A1,1,0,0,1,14,15Z"
        />
        <rect
          className="fill-current"
          x="4"
          y="7"
          width="2"
          height="2"
          rx="1"
          ry="1"
        />
        <rect
          className="fill-current"
          x="7"
          y="7"
          width="2"
          height="2"
          rx="1"
          ry="1"
        />
        <rect
          className="fill-current"
          x="10"
          y="7"
          width="2"
          height="2"
          rx="1"
          ry="1"
        />
        <rect
          className="fill-current"
          x="4"
          y="10"
          width="2"
          height="2"
          rx="1"
          ry="1"
        />
        <rect
          className="fill-current"
          x="7"
          y="10"
          width="2"
          height="2"
          rx="1"
          ry="1"
        />
        <rect
          className="fill-current"
          x="10"
          y="10"
          width="2"
          height="2"
          rx="1"
          ry="1"
        />
        <path
          className="fill-none stroke-currentcolor"
          d="M2,1H14a1,1,0,0,1,1,1V3a0,0,0,0,1,0,0H1A0,0,0,0,1,1,3V2A1,1,0,0,1,2,1Z"
        />
      </symbol>
      <symbol id="design-16" viewBox="0 0 16 16">
        <g className="design">
          <g className="fill-(--icon-fill) stroke-current stroke-2 sl-s">
            <path d="M3 12c0-2.76 2.24-5 5-5s5 2.24 5 5" />
            <path d="M3 12c0-2.76 2.24-5 5-5s5 2.24 5 5" />
          </g>
          <path
            d="M2 7h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M9 6H7v2h2V6Z"
            className="fill-current stroke-current stroke-2 sl-r"
          />
          <path
            d="M2 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"
            className="fill-current stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"
            className="fill-current stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="download-16" viewBox="0 0 16 16">
        <g className="download">
          <path
            d="M2 15h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <g className="fill-none stroke-current stroke-2 sl-r">
            <path d="m5 8 3 3 3-3" />
            <path d="m5 8 3 3 3-3" />
          </g>
          <path d="M8 1v9" className="fill-none stroke-current stroke-2 sl-r" />
        </g>
      </symbol>
      <symbol id="dropdown-16" viewBox="0 0 16 16">
        <path d="M8.27,10.58a.5.5,0,0,1-.54,0l-5.7-7A.5.5,0,0,1,2.3,3h11.4a.5.5,0,0,1,.27.92Z" />
      </symbol>
      <symbol id="enlarge-16" viewBox="0 0 16 16">
        <g className="enlarge">
          <path
            d="M2 11v3h3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 5V2h-3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M5 2H2v3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m14 2-4 4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m6 10-4 4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m2 2 4 4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m10 10 4 4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M11 14h3v-3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="enter-16" viewBox="0 0 16 16">
        <g className="enter">
          <path
            d="M3 8h10V4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M4 6 2 8l2 2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="envelope-16" viewBox="0 0 16 16">
        <g className="envelope">
          <g className="fill-(--icon-fill) stroke-current stroke-2 sl-r">
            <path d="M2 5.29 1 6v9h14V6l-1-.72" />
            <path d="M2 5.29 1 6v9h14V6l-1-.72" />
          </g>
          <path
            d="M14 7V3H2v4H1l7 4 7-4h-1Z"
            className="fill-(--icon-fill-bg)"
          />
          <path
            d="m1 7 7 4 7-4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M10.8 3 8 1"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M8 1 5.2 3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M2 7V3h12v4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="expand-16" viewBox="0 0 16 16">
        <g className="expand">
          <path
            d="M10 2h4v4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 2H2v4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M10 14h4v-4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 14H2v-4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="external-16" viewBox="0 0 16 16">
        <g className="external">
          <rect
            width="8"
            height="8"
            x="3"
            y="5"
            className="fill-(--icon-fill)"
            rx="1"
          />
          <path
            d="m7 9 7-7"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M9 2h5v5"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 5H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="external-1-16" viewBox="0 0 16 16">
        <path d="M6 10L14 2" className="stroke-current stroke-2 slc-r sl-r" />
        <path
          d="M10 2L14 2L14 6"
          className="stroke-current stroke-2 slc-r sl-r"
        />
        <path
          d="M6 2H3C2.44772 2 2 2.44772 2 3V13C2 13.5523 2.44772 14 3 14H13C13.5523 14 14 13.5523 14 13V10"
          className="stroke-current stroke-2 slc-r sl-r"
        />
      </symbol>
      <symbol id="folder-16" viewBox="0 0 16 16">
        <g className="folder">
          <path
            d="M2 6h12v7a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M3 3a1 1 0 0 1 1-1h2l2 1h4a1 1 0 0 1 1 1v2H3V3Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="font-16" viewBox="0 0 16 16">
        <g className="font">
          <path
            d="m3 4 .625-2 .535.214a4 4 0 0 0 1.485.286h4.71a4 4 0 0 0 1.485-.286L12.375 2 13 4a2.438 2.438 0 0 0-2.25-1.5H10C9.375 2.5 8 3 8 4c0-1-1.375-1.5-2-1.5h-.75C4.266 2.5 3.378 3.092 3 4Z"
            className="Vector 35"
          />
          <path
            d="M8 3v10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 14h4Z"
            className="fill-none stroke-current stroke-2 sl-s"
          />
        </g>
      </symbol>
      <symbol id="font-outline-16" viewBox="0 0 16 16">
        <path
          className="fill-(--icon-fill) stroke-2"
          stroke="color(display-p3 .0353 .1804 .1412)"
          d="M4.104 2.385 3.334 2l-.667 4.667s.666-1.334 2.666-1.334h1.334V10c0 1.333-.667 2-1.334 2v2h5.334v-2c-.667 0-1.334-.667-1.334-2V5.333h1.334c2 0 2.666 1.334 2.666 1.334L12.667 2l-.77.385c-.37.185-.78.282-1.193.282H5.296c-.414 0-.822-.097-1.192-.282Z"
        />
      </symbol>
      <symbol id="foundry-16" viewBox="0 0 16 16">
        <g className="foundry">
          <path
            d="M2.662 14C2.294 14 2 13.702 2 13.333V2.667C2 2.298 2.298 2 2.667 2C6.222 2 9.778 2 13.333 2C13.702 2 14 2.298 14 2.667V13.333C14 13.702 13.705 14 13.337 14C11.259 14 4.882 14 2.662 14Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M5 6V5H11V6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M8 5V11"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M7 11H9"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="frame-16" viewBox="0 0 16 16">
        <g className="frame">
          <path d="M4 4h8v8H4z" className="fill-(--icon-fill)" />
          <path
            d="M2 4h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M4 2v12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M12 2v12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M2 12h12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="home-16" viewBox="0 0 16 16">
        <g className="home">
          <path
            d="M15 7 8 1 1 7h1v8h4V9h4v6h4V7h1Z"
            className="fill-(--icon-fill)"
          />
          <path
            d="m1 7 7-6 7 6"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M2 6.33V15h4V9h4v6h4V6.33"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 14h4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="link-16" viewBox="0 0 16 16">
        <g className="link">
          <path
            d="M13.084 7.337a3.126 3.126 0 1 0-4.42-4.421l-1.77 1.768a3.126 3.126 0 0 0 0 4.421m-3.978-.442a3.126 3.126 0 1 0 4.42 4.421l1.77-1.768a3.126 3.126 0 0 0 0-4.421"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="move-16" viewBox="0 0 16 16">
        <g className="move">
          <path
            d="m6 12 2 2 2-2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M10 4 8 2 6 4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M4 6 2 8l2 2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M10 8h3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path d="M3 8h3" className="fill-none stroke-current stroke-2 sl-r" />
          <path d="M8 3v3" className="fill-none stroke-current stroke-2 sl-r" />
          <path
            d="M8 10v3"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m12 10 2-2-2-2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="navigation-16" viewBox="0 0 16 16">
        <g className="navigation">
          <path d="M13 4H3" className="stroke-current stroke-2 sl-r" />
          <path d="M13 12H3" className="stroke-current stroke-2 sl-r" />
        </g>
      </symbol>
      <symbol id="newsletter-16" viewBox="0 0 16 16">
        <path
          d="M15 8 5 14v-4l3-2-3-2V2l10 6Z"
          fill="#EEEAEC"
          className="stroke-currentcolor"
        />
        <path d="M2 8H1M13 8H8" className="stroke-currentcolor" />
        <circle cx="2" cy="4" r="1" className="fill-current" stroke="none" />
        <circle cx="2" cy="12" r="1" className="fill-current" stroke="none" />
      </symbol>
      <symbol id="note-16" viewBox="0 0 16 16">
        <g className="note">
          <g className="fill-(--icon-fill) stroke-current stroke-2 sl-r">
            <path d="M3.5 14a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H12a1 1 0 0 1 1 1v6l-5 5H3.5Z" />
            <path d="M8 14v-4a1 1 0 0 1 1-1h4m-5 5H3.5a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H12a1 1 0 0 1 1 1v6m-5 5 5-5" />
          </g>
          <path d="M10 6H6" className="stroke-current stroke-2 sl-r" />
        </g>
      </symbol>
      <symbol id="note-pencil-16" viewBox="0 0 16 16">
        <g className="note-pencil">
          <rect
            width="10.667"
            height="12"
            x="2.667"
            y="2"
            className="fill-(--icon-fill)"
            rx=".667"
          />
          <path d="M10 10H6" className="stroke-current stroke-2 sl-r" />
          <path
            d="M8.667 2H3.333a.667.667 0 0 0-.666.667v10.666c0 .368.298.667.666.667h9.334a.667.667 0 0 0 .666-.667V6.667"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M12 2 8.667 5.333v1.334H10l3.333-3.334L12 2Z"
            className="Vector 33"
          />
        </g>
      </symbol>
      <symbol id="note-plus-16" viewBox="0 0 16 16">
        <g className="note-plus">
          <rect
            width="10"
            height="12"
            x="3"
            y="2"
            className="fill-(--icon-fill)"
            rx=".667"
          />
          <path d="M10 6H6" className="stroke-current stroke-2 sl-r" />
          <path
            d="M8.333 14H3.667A.667.667 0 0 1 3 13.333V2.667C3 2.298 3.298 2 3.667 2h8.666c.368 0 .667.298.667.667V8"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path d="M11.5 12.5h3" className="stroke-current stroke-2 sl-r" />
          <path d="M13 11v3" className="stroke-current stroke-2 sl-r" />
        </g>
      </symbol>
      <symbol id="notepad-16" viewBox="0 0 16 16">
        <g className="notepad">
          <path
            d="M4 14a1 1 0 0 1-1-1V2.667C3 2.298 3.298 2 3.667 2h8.666c.368 0 .667.298.667.667V13c0 .552-.444 1-.996 1H4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path d="M6 2v2" className="stroke-current stroke-2 sl-r" />
          <path d="M10 2v2" className="stroke-current stroke-2 sl-r" />
          <path d="M6 7h2" className="stroke-current stroke-2 sl-r" />
          <path d="M6 10h4" className="stroke-current stroke-2 sl-r" />
        </g>
      </symbol>
      <symbol id="palette-16" viewBox="0 0 16 16">
        <g className="palette">
          <path
            d="M2 8a6 6 0 1 1 12 0v1.547c0 .25-.203.453-.453.453h-2.214c-.736 0-1.333.597-1.333 1.333v2.214c0 .25-.203.453-.453.453H8a6 6 0 0 1-6-6Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <circle cx="8" cy="5" r="1" className="fill-current" />
          <circle cx="7" cy="10" r="1" className="fill-current" />
          <circle cx="5" cy="7" r="1" className="fill-current" />
        </g>
      </symbol>
      <symbol id="pen-16" viewBox="0 0 16 16">
        <g className="pen">
          <path
            d="M11 15H5c0-3-3-6-3-6l6-8 6 8s-3 3-3 6Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path d="M8 2v7" className="fill-none stroke-current stroke-2 sl-r" />
          <circle
            cx="8"
            cy="9"
            r="1"
            className="fill-current stroke-current stroke-1 sl-r"
          />
          <path
            d="M4 15h8"
            className="fill-none stroke-current stroke-2 sl-s"
          />
        </g>
      </symbol>
      <symbol id="person-16" viewBox="0 0 16 16">
        <g className="person">
          <path
            d="M9.84 9.7v-.03c.9-.72 1.49-1.94 1.49-3.33v-2c0-1.21 0-2-.67-2.67C10 1 9.33 1 8.67 1c-.6 0-.66.54-1.64.65-1.37.15-2.36 1.37-2.36 2.74v1.94c0 1.39.59 2.62 1.49 3.33v.03c-.09 1.21-.93 1.21-2.09 1.57-.62.19-1.14.4-1.56.59-.71.33-1.17 1.04-1.17 1.82V14c0 .55.45 1 1 1h11.33c.55 0 1-.45 1-1v-.32c0-.78-.45-1.49-1.17-1.82-.42-.19-.95-.4-1.56-.59-1.16-.36-2.01-.36-2.1-1.57Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="play-16" viewBox="0 0 16 16">
        <g className="play">
          <path
            d="M3 2.741a1 1 0 0 1 1.504-.864l9.015 5.26a1 1 0 0 1 0 1.727l-9.015 5.259A1 1 0 0 1 3 13.259V2.741Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="plus-16" viewBox="0 0 16 16">
        <g className="plus">
          <path
            d="M3 8h10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M8 3v10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="publication-16" viewBox="0 0 16 16">
        <g className="publication">
          <path
            d="M3 14C2.448 14 2 13.552 2 13V3C2 2.448 2.448 2 3 2H13C13.552 2 14 2.448 14 3V13C14 13.552 13.552 14 13 14Z"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M5 6H11"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 9H10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="puzzle-16" viewBox="0 0 16 16">
        <g className="puzzle">
          <path
            d="M2 2.5a.5.5 0 0 1 .5-.5h8.889a.5.5 0 0 1 .5.5v2.645c0 .382.424.642.793.544C13.604 5.444 15 5.489 15 8c0 2.512-1.396 2.556-2.318 2.311-.37-.098-.793.162-.793.544V13.5a.5.5 0 0 1-.5.5H2.5a.5.5 0 0 1-.5-.5v-2.732c0-.362.38-.618.734-.55.92.177 2.377.092 2.377-2.218S3.654 5.605 2.734 5.782C2.38 5.85 2 5.594 2 5.232V2.5Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="rectangle-16" viewBox="0 0 16 16">
        <g className="rectangle">
          <rect
            width="10"
            height="10"
            x="3"
            y="3"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            rx="1"
          />
        </g>
      </symbol>
      <symbol id="save-16" viewBox="0 0 16 16">
        <line x1="2" y1="15" x2="14" y2="15" />
        <polyline className="fill-s1" points="5 8 8 11 11 8" />
        <line x1="8" y1="1" x2="8" y2="10" />
      </symbol>
      <symbol id="saved-16" viewBox="0 0 16 16">
        <line x1="2" y1="15" x2="14" y2="15" />
        <polyline points="3 8 6 11 13 4" />
      </symbol>
      <symbol id="search-16" viewBox="0 0 16 16">
        <g className="search">
          <path
            d="m11 11 2 2"
            className="fill-none stroke-current stroke-4 sl-r"
          />
          <circle
            cx="7"
            cy="7"
            r="5"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="search-small-16" viewBox="0 0 16 16">
        <path d="M11 11L14 14" className="sw-4" />
        <circle cx="7" cy="7" r="5" className="fill-(--icon-fill) sw-2" />
      </symbol>
      <symbol id="settings-16" viewBox="0 0 16 16">
        <g className="settings">
          <circle
            cx="5"
            cy="4"
            r="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <circle
            cx="11"
            cy="12"
            r="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path d="M5 6v9" className="fill-none stroke-current stroke-2" />
          <path d="M11 1v9" className="fill-none stroke-current stroke-2" />
        </g>
      </symbol>
      <symbol id="shadow-16" viewBox="0 0 16 16">
        <g className="shadow">
          <circle
            cx="8"
            cy="6"
            r="4"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M3.101 12a6.977 6.977 0 0 0 4.9 2 6.977 6.977 0 0 0 4.898-2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="shapes-16" viewBox="0 0 16 16">
        <g className="shapes">
          <circle
            cx="4"
            cy="12"
            r="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <circle
            cx="12"
            cy="4"
            r="2"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 10h-4v4h4v-4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M6 2H2v4h4V2Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="share-16" viewBox="0 0 16 16">
        <g className="share">
          <g className="Group 2">
            <rect
              width="10"
              height="6"
              x="3"
              y="7"
              className="fill-(--icon-fill)"
              rx="1"
            />
            <path
              d="M5.143 7H3.5a.5.5 0 0 0-.5.5v5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-5a.5.5 0 0 0-.5-.5h-1.643"
              className="fill-none stroke-current stroke-2 sl-r"
            />
            <path
              d="M8 3v6"
              className="fill-none stroke-current stroke-2 sl-r"
            />
            <path
              d="M10 4 8 2 6 4"
              className="fill-none stroke-current stroke-2 sl-r"
            />
          </g>
        </g>
      </symbol>
      <symbol id="sidebar-left-16" viewBox="0 0 16 16">
        <g className="sidebar-left">
          <path
            d="M3.5 14A1.5 1.5 0 0 1 2 12.5v-9A1.5 1.5 0 0 1 3.5 2h1A1.5 1.5 0 0 1 6 3.5v9A1.5 1.5 0 0 1 4.5 14h-1Z"
            className="fill-(--icon-fill)"
          />
          <rect
            width="12"
            height="12"
            x="2"
            y="2"
            className="fill-(--icon-fill-bg) stroke-current stroke-2 sl-r"
            rx="1"
          />
          <path
            d="M6 3v10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="sidebar-right-16" viewBox="0 0 16 16">
        <g className="sidebar-right">
          <path
            d="M11.5 14a1.5 1.5 0 0 1-1.5-1.5v-9A1.5 1.5 0 0 1 11.5 2h1A1.5 1.5 0 0 1 14 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-1Z"
            className="fill-(--icon-fill)"
          />
          <rect
            width="12"
            height="12"
            x="2"
            y="2"
            className="fill-(--icon-fill-bg) stroke-current stroke-2 sl-r"
            rx="1"
          />
          <path
            d="M10 3v10"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="star-16" viewBox="0 0 16 16">
        <g className="star">
          <path
            d="M7.407 2.154a.667.667 0 0 1 1.186 0l1.36 2.647c.097.188.277.32.486.353l2.937.476a.667.667 0 0 1 .367 1.128l-2.097 2.11a.666.666 0 0 0-.186.572l.456 2.94a.667.667 0 0 1-.96.698l-2.655-1.342a.667.667 0 0 0-.602 0l-2.655 1.342a.667.667 0 0 1-.96-.697l.456-2.94a.667.667 0 0 0-.186-.572L2.257 6.758a.667.667 0 0 1 .367-1.128l2.937-.476a.667.667 0 0 0 .486-.353l1.36-2.647Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="tab-16" viewBox="0 0 16 16">
        <g className="tab">
          <path
            d="M13 8H2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M9 12L13 8L9 4"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 4V12"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="time-16" viewBox="0 0 16 16">
        <circle className="fill-s1" cx="8" cy="9" r="5.5" />
        <line x1="2" y1="3.5" x2="4" y2="1.5" />
        <line x1="14" y1="3.5" x2="12" y2="1.5" />
        <polyline points="8 7 8 9 10 9" />
      </symbol>
      <symbol id="timer-16" viewBox="0 0 16 16">
        <g className="timer">
          <path
            d="M8 14.5a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="m2 3.5 2-2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="m14 3.5-2-2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M8 7v2h2"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="type-16" viewBox="0 0 16 16">
        <g className="type">
          <path d="m8 3 1 1v6H5l3-7Z" className="fill-(--icon-fill)" />
          <g className="mask-type-16">
            <mask
              id="type-16-a"
              width="8"
              height="14"
              x="1"
              y="1"
              maskUnits="userSpaceOnUse"
              style={{ maskType: 'alpha' }}
            >
              <path d="M1 1h8v14H1z" />
            </mask>
            <g mask="url(#type-16-a)">
              <path
                d="M4 11h5"
                className="fill-none stroke-current stroke-2 sl-r"
              />
              <path
                d="M2 16 7.76 2 14 16"
                className="fill-none stroke-current stroke-2 sl-r"
              />
            </g>
          </g>
          <path
            d="M11 2h1v12h-1"
            className="fill-none stroke-current stroke-2 sl-r"
          />
          <path
            d="M13 2h-1v12h1"
            className="fill-none stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="vector-square-16" viewBox="0 0 16 16">
        <g className="vector-square">
          <path
            d="M4 13a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v8c0 .552-.444 1-.996 1H4Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M4 2H2v2h2V2Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M4 12H2v2h2v-2Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 2h-2v2h2V2Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
          <path
            d="M14 12h-2v2h2v-2Z"
            className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
          />
        </g>
      </symbol>
      <symbol id="views-16" viewBox="0 0 16 16">
        <g className="views">
          <g className="fill-(--icon-fill) stroke-current stroke-2 sl-r">
            <path
              d="M2 4h4v10H2z"
              className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            />
            <path
              d="M6 6h4v8H6z"
              className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            />
            <path
              d="M10 2h4v12h-4z"
              className="fill-(--icon-fill) stroke-current stroke-2 sl-r"
            />
          </g>
        </g>
      </symbol>
    </defs>
  </svg>
)

export default Sprite16
